baseURL = 'https://symph0ny.github.io/Sinalefa'
languageCode = 'es-419'
title = 'Sinalefa'
PygmentsCodeFences = true
defaultcontentlanguage = 'es'
copyright = "© Symph0ny"
PygmentsStyle = "monokai"
pluralizelisttitles = "false"
paginate = 7
disableHugoGeneratorInject = false
enableEmoji = true
theme = "archie"

[params]
	mode = "toggle" # Opciones: dark, light, auto, toggle
	useCDN = false
	subtitle = "¡Hola!, soy Symph0ny. Este es mi blog, Sinalefa."
	mathjax = true
	katex = false

menu.items = [
    {name = "Inicio", weight = 1, url = "$BASEURL/"},
		{name = "Blog", weight = 2, url = "$BASEURL/blog"},
		{name = "Sobre mí", weight = 3, url = "$BASEURL/about"},
    {name = "Etiquetas", weight = 4, url = "$BASEURL/tags"},
]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.3"  
